from __future__ import annotations

from .models import SignalKind, SourceRecord

SOURCES: list[SourceRecord] = [
    SourceRecord(
        id="companies-house",
        name="Companies House",
        canonical_url="https://www.gov.uk/government/organisations/companies-house",
        category="companies",
        jurisdiction="GB",
        licence="Open Government Licence where applicable; verify dataset-specific terms",
        commercial_reuse=None,
        refresh_cadence="source-dependent",
        collection_method="api",
        entity_types=["company", "officer", "filing", "charge", "insolvency"],
        supported_signals=[
            SignalKind.DIRECTOR_CHANGE,
            SignalKind.HEADCOUNT_GROWTH,
            SignalKind.DISTRESS,
        ],
        notes="Treat filing-derived inference separately from statutory facts.",
    ),
    SourceRecord(
        id="contracts-finder",
        name="Contracts Finder",
        canonical_url="https://www.gov.uk/contracts-finder",
        category="procurement",
        jurisdiction="GB",
        licence="Verify record/feed terms before redistribution",
        commercial_reuse=None,
        refresh_cadence="daily",
        collection_method="api_or_feed",
        entity_types=["buyer", "supplier", "contract", "notice"],
        supported_signals=[SignalKind.PUBLIC_CONTRACT_WIN, SignalKind.PROCUREMENT_ACTIVITY],
    ),
    SourceRecord(
        id="find-a-tender",
        name="Find a Tender",
        canonical_url="https://www.gov.uk/find-tender",
        category="procurement",
        jurisdiction="GB",
        licence="Verify notice/feed terms before redistribution",
        commercial_reuse=None,
        refresh_cadence="daily",
        collection_method="api_or_feed",
        entity_types=["buyer", "supplier", "contract", "notice"],
        supported_signals=[SignalKind.PUBLIC_CONTRACT_WIN, SignalKind.PROCUREMENT_ACTIVITY],
    ),
    SourceRecord(
        id="ons",
        name="Office for National Statistics",
        canonical_url="https://www.ons.gov.uk/",
        category="economics",
        jurisdiction="GB",
        licence="Open Government Licence for many datasets; verify dataset-specific terms",
        commercial_reuse=None,
        refresh_cadence="dataset-dependent",
        collection_method="api_or_download",
        entity_types=["industry", "geography", "labour_market", "economic_series"],
        supported_signals=[SignalKind.HIRING_GROWTH, SignalKind.MARKET_GROWTH],
    ),
    SourceRecord(
        id="nomis",
        name="Nomis",
        canonical_url="https://www.nomisweb.co.uk/",
        category="labour_market",
        jurisdiction="GB",
        licence="Verify dataset-specific terms",
        commercial_reuse=None,
        refresh_cadence="dataset-dependent",
        collection_method="api",
        entity_types=["geography", "occupation", "industry", "labour_market"],
        supported_signals=[SignalKind.HIRING_GROWTH, SignalKind.MARKET_GROWTH],
    ),
    SourceRecord(
        id="gdelt",
        name="GDELT Global Events Database",
        canonical_url="https://www.gdeltproject.org/",
        category="news_events",
        jurisdiction=None,
        licence="Public data; verify GDELT terms and downstream article rights before redistribution",
        commercial_reuse=None,
        refresh_cadence="near-real-time",
        collection_method="api",
        entity_types=["organisation", "event", "news_article", "location", "theme"],
        supported_signals=[
            SignalKind.MARKET_GROWTH,
            SignalKind.DISTRESS,
            SignalKind.FUNDING_EVENT,
            SignalKind.NEW_LOCATION,
        ],
        notes="Use as a discovery/event signal source; retain links and metadata rather than article text.",
    ),
    SourceRecord(
        id="world-bank",
        name="World Bank Open Data",
        canonical_url="https://data.worldbank.org/",
        category="macroeconomics",
        jurisdiction=None,
        licence="World Bank dataset-specific terms apply; verify before redistribution",
        commercial_reuse=None,
        refresh_cadence="indicator-dependent",
        collection_method="api",
        entity_types=["country", "indicator", "economy", "sector"],
        supported_signals=[SignalKind.MARKET_GROWTH],
        notes="Useful for country and market-entry context, not company-level facts.",
    ),
    SourceRecord(
        id="eurostat",
        name="Eurostat",
        canonical_url="https://ec.europa.eu/eurostat/",
        category="economics",
        jurisdiction="EU",
        licence="Eurostat reuse policy applies; verify dataset-specific notices",
        commercial_reuse=None,
        refresh_cadence="dataset-dependent",
        collection_method="api_or_download",
        entity_types=["country", "region", "industry", "labour_market", "economic_series"],
        supported_signals=[SignalKind.MARKET_GROWTH, SignalKind.HIRING_GROWTH],
        notes="Adds EU market, sector, labour and regional comparison context.",
    ),
    SourceRecord(
        id="oecd",
        name="OECD Data",
        canonical_url="https://data.oecd.org/",
        category="economics",
        jurisdiction=None,
        licence="OECD terms and dataset-specific reuse conditions apply",
        commercial_reuse=None,
        refresh_cadence="dataset-dependent",
        collection_method="api_or_download",
        entity_types=["country", "industry", "productivity", "trade", "labour_market"],
        supported_signals=[SignalKind.MARKET_GROWTH, SignalKind.HIRING_GROWTH],
        notes="Best suited to international benchmarking and market-entry scoring.",
    ),
    SourceRecord(
        id="wikidata",
        name="Wikidata",
        canonical_url="https://www.wikidata.org/",
        category="knowledge_graph",
        jurisdiction=None,
        licence="CC0 for structured Wikidata content",
        commercial_reuse=True,
        refresh_cadence="continuous",
        collection_method="api_or_sparql",
        entity_types=["organisation", "person", "industry", "location", "subsidiary", "brand"],
        supported_signals=[SignalKind.NEW_LOCATION, SignalKind.MARKET_GROWTH],
        notes="Use for entity resolution and relationship enrichment; never override stronger statutory sources.",
    ),
    SourceRecord(
        id="common-crawl",
        name="Common Crawl",
        canonical_url="https://commoncrawl.org/",
        category="web_archive",
        jurisdiction=None,
        licence="Crawl data is public; underlying page content retains source rights",
        commercial_reuse=None,
        refresh_cadence="monthly",
        collection_method="index_api_or_archive",
        entity_types=["domain", "web_page", "website_history"],
        supported_signals=[SignalKind.DIGITAL_TRANSFORMATION, SignalKind.AUTOMATION_GAP],
        notes="Use primarily for domain existence/history and public web-change evidence, not bulk republication.",
    ),
    SourceRecord(
        id="openstreetmap",
        name="OpenStreetMap",
        canonical_url="https://www.openstreetmap.org/",
        category="geospatial",
        jurisdiction=None,
        licence="Open Database Licence (ODbL); attribution and share-alike requirements apply",
        commercial_reuse=True,
        refresh_cadence="continuous",
        collection_method="api_or_download",
        entity_types=["location", "place", "site", "amenity", "geography"],
        supported_signals=[SignalKind.NEW_LOCATION, SignalKind.MARKET_GROWTH],
        notes="Use for location intelligence and proximity context; respect API usage policies.",
    ),
    SourceRecord(
        id="openaddresses",
        name="OpenAddresses",
        canonical_url="https://openaddresses.io/",
        category="geospatial",
        jurisdiction=None,
        licence="Source-level licences vary; inspect per-country/per-source attribution requirements",
        commercial_reuse=None,
        refresh_cadence="source-dependent",
        collection_method="download",
        entity_types=["address", "location", "geography"],
        supported_signals=[SignalKind.NEW_LOCATION],
        notes="Useful for address normalisation and geographic entity resolution where licensing permits.",
    ),
    SourceRecord(
        id="website-technology",
        name="Public company website technology profile",
        canonical_url="https://github.com/Raebu/Raeburn-Intelligence-OS",
        category="technology",
        jurisdiction=None,
        licence="Observed public metadata only; respect target-site terms and access controls",
        commercial_reuse=None,
        refresh_cadence="on-demand",
        collection_method="public_web_observation",
        entity_types=["website", "technology"],
        supported_signals=[SignalKind.DIGITAL_TRANSFORMATION, SignalKind.AUTOMATION_GAP],
        notes="Uses visible HTML and response headers; does not bypass authentication or controls.",
    ),
    SourceRecord(
        id="public-careers-page",
        name="Public company careers page",
        canonical_url="https://github.com/Raebu/Raeburn-Intelligence-OS",
        category="jobs",
        jurisdiction=None,
        licence="Observed public page signals only; respect target-site terms and access controls",
        commercial_reuse=None,
        refresh_cadence="on-demand",
        collection_method="public_web_observation",
        entity_types=["job", "career_page"],
        supported_signals=[SignalKind.TECH_HIRING, SignalKind.HIRING_GROWTH],
        notes="Hiring growth is derived only when historical scans show an increase.",
    ),
    SourceRecord(
        id="data-gov-uk",
        name="data.gov.uk",
        canonical_url="https://www.data.gov.uk/",
        category="dataset_catalogue",
        jurisdiction="GB",
        licence="Per-dataset",
        commercial_reuse=None,
        refresh_cadence="catalogue-dependent",
        collection_method="catalogue",
        entity_types=["dataset"],
        supported_signals=[],
        notes="Discovery catalogue only. Licence and source quality must be assessed per dataset.",
    ),
    SourceRecord(
        id="awesome-public-datasets",
        name="Awesome Public Datasets",
        canonical_url="https://github.com/awesomedata/awesome-public-datasets",
        category="dataset_catalogue",
        jurisdiction=None,
        licence="Repository and linked datasets have separate licensing considerations",
        commercial_reuse=None,
        refresh_cadence="community-maintained",
        collection_method="catalogue",
        entity_types=["dataset"],
        supported_signals=[],
        notes=(
            "Use for source discovery, never as blanket permission to ingest or redistribute linked data."
        ),
    ),
]


def get_sources() -> list[SourceRecord]:
    return SOURCES


def get_source(source_id: str) -> SourceRecord | None:
    return next((source for source in SOURCES if source.id == source_id), None)
